# Generated by Django 6.0.6 on 2026-06-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
