# Generated by Django 6.0.6 on 2026-06-15 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_upcominggame'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Short introductory summary of the review.')),
                ('gameplay_review', models.TextField()),
                ('graphics_performance_review', models.TextField()),
                ('pros', models.TextField(help_text='Enter pros separated by commas.')),
                ('cons', models.TextField(help_text='Enter cons separated by commas.')),
                ('rating', models.PositiveIntegerField(help_text='Enter a score from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
